extends: conditional
message: "'%s': Spell out acronyms the first time that you use them on a page and follow them with the acronym in parentheses. Subsequently, use the acronym alone."
link: 'https://github.com/opensearch-project/documentation-website/blob/main/STYLE_GUIDE.md#acronyms'
level: warning
scope: summary
ignorecase: false
# Ensures that the existence of 'first' implies the existence of 'second'.
first: '\b((?<!k-)[A-Z]{1,3}\/?[A-Z]{1,3}\d{0,2}\b(?!\sCommons))'
second: '(?:\b[A-Za-z-]+ )+\(([A-Z]{1,3}\/?[A-Z]{1,3}\d{0,2})\)'
# ... with the exception of these:
exceptions:
  - API
  - ASCII
  - AWS
  - BASIC
  - BM25
  - CPU
  - DOS
  - FAQ
  - FTP
  - GIF
  - HTML
  - HTTP
  - HTTPS
  - I/O
  - ID
  - IP
  - JPEG
  - JSON
  - NAT
  - NGINX
  - PDF
  - RAM
  - REST
  - RGB
  - ROM
  - SAML
  - SDK
  - SSL
  - TCP
  - TIFF
  - TLS
  - UI
  - URI
  - URL
  - UTC
  - UTF
  - XML
  - YAML
  - CAT
  - GET
  - PUT
  - POST
  - DELETE
  - AND
  - OR
  - KB
  - MB
  - GB
  - TB
  - PB
  - US
  - PNG
  - JVM
  - N/A
  - GROUP
  - BY
  - SELECT
  - HAVING
  - SQL
  - TOC
  - 'NULL'