extends: substitution
message: "Use '%s' instead of '%s' because the latter is an offensive term."
link: https://github.com/opensearch-project/documentation-website/blob/main/STYLE_GUIDE.md#offensive-terms
ignorecase: true
level: error
swap:
  'black day': blocked day
  'blacklist': deny list
  'master node': cluster manager node
  'slave': replica, secondary, standby
  'white day': open day
  'whitelist': allow list
