extends: substitution
message: "Use '%s' instead of '%s'."
link: https://github.com/opensearch-project/documentation-website/blob/main/STYLE_GUIDE.md#basic-guidelines
ignorecase: true
level: warning
nonword: true
action:
  name: replace
swap:
  '\b(?:eg|e\.g\.)[\s,]': for example or such as
  '\b(?:ie|i\.e\.)[\s,]': that is or specifically
  'ad hoc': one-time
  '\b(?:v\.|vs\.|vs|versus)': compared to or compared with
  'via': using, through, by accessing, or by choosing
  'vice versa': the other way around