extends: substitution
message: "'%s': Use 'AWS Signature Version 4' instead of '%s' on first appearance. Then, Signature Version 4 may be used. Only use SigV4 when space is limited."
ignorecase: true
link: 'https://github.com/opensearch-project/documentation-website/blob/main/TERMS.md'
level: warning
action:
  name: replace
swap:
  sigv4: Signature Version 4
  AWS sigv4: AWS Signature Version 4
  