extends: existence
message: "Don't use '%s' because it's not neutral in tone. If you mean 'only', use 'only' instead."
link: https://github.com/opensearch-project/documentation-website/blob/main/TERMS.md
ignorecase: true
level: warning
action:
  name: remove
tokens:
  - simply
  - just
