extends: substitution
message: "Use '%s' instead of '%s'. Note the correct capitalization."
ignorecase: false
level: error
action:
  name: replace
swap:
  'Retrieval-Augmented Generation': retrieval-augmented generation
  'base-64': Base64
  'Base-64': Base64
  'base 64': Base64
  'Base 64': Base64
  'base64-encoded': Base64-encoded