extends: substitution
message: "Use '%s' instead of '%s'."
ignorecase: true
level: suggestion
action:
  name: replace
swap:
  'app server': application server
  'as well as': and
  'due to': because of
  'it is recommended': we recommend
  'leverage': use
  'life cycle': lifecycle
  'navigate in': navigate to
  'wish|desire': want
  