extends: substitution
message: "Use '%s' instead of '%s'."
ignorecase: true
level: warning
action:
  name: replace
swap:
  'async': asynchronous
  'auth': authentication or authorization
  'config': configuration
