extends: substitution
message: "Use '%s' instead of '%s'."
ignorecase: true
level: suggestion
action:
  name: replace
swap:
  'app server': application server
  'as well as': and
  'due to': because of
  'get': receive, obtain, or retrieve
  'gets': receives, returns, or retrieves
  'getting': retrieving or obtaining
  'handle': manage, process, or resolve
  'handles': manages, processes, or resolves
  'handling': managing, processing, or resolving
  'it is recommended': we recommend
  'leverage': use
  'life cycle': lifecycle
  'navigate in': navigate to
  'set up': configure
  'sets up': configures
  'setting up': configuring
  'spin up': create or launch
  'spins up': creates or launches
  'clean up': remove
  'cleans up': removes
  'cleaning up': removing
  'simple': (remove or rephrase)
  'simply': (remove or rephrase)
  'teardown': removal
  'tear down': remove
  'wish|desire': want
  