# SPDX-License-Identifier: Apache-2.0
#
# The OpenSearch Contributors require contributions made to
# this file be licensed under the Apache-2.0 license or a
# compatible open source license.

# frozen_string_literal: true

require 'rake'
require 'active_support/all'
require_relative 'lib/coverage/utilization_coverage'
require_relative 'lib/utils'

desc 'Generate utilization coverage of Spec-Insert components'
task :generate_utilization_coverage do
  Utils.load_spec
  coverage = UtilizationCoverage.new.render
  file = File.join(__dir__, 'utilization_coverage.md')
  File.write(file, coverage)
  puts "Utilization coverage written to #{file}"
end
