openapi: 3.1.0
info:
  title: OpenSearch API Specification
  version: 1.0.0
  x-api-version: 2.16.0
paths:
  /_cat/health:
    get:
      operationId: cat_health.0
      x-operation-group: cat.health
      parameters:
        - $ref: '#/components/parameters/_global___query.pretty'
        - $ref: '#/components/parameters/_global___query.human'
        - $ref: '#/components/parameters/cat.health___query.expand_wildcard'
  /_search:
    get:
      operationId: search.0
      x-operation-group: search
      x-version-added: '1.0'
      description: Returns results matching a query.
      externalDocs:
        url: https://docs.opensearch.org/latest/api-reference/search/
      parameters:
        - $ref: '#/components/parameters/search___query.analyze_wildcard'
        - $ref: '#/components/parameters/search___query.analyzer'
    post:
      operationId: search.1
      x-operation-group: search
      x-version-added: '1.0'
      description: Returns results matching a query.
      externalDocs:
          url: https://docs.opensearch.org/latest/api-reference/search/
      parameters:
          - $ref: '#/components/parameters/search___query.analyze_wildcard'
          - $ref: '#/components/parameters/search___query.analyzer'
          - $ref: '#/components/parameters/search___query.expand_wildcards'
  /{index}/_search:
    get:
      operationId: search.2
      x-operation-group: search
      x-version-added: '1.0'
      description: Returns results matching a query.
      externalDocs:
        url: https://docs.opensearch.org/latest/api-reference/search/
      parameters:
        - $ref: '#/components/parameters/search___path.index'
        - $ref: '#/components/parameters/search___query.analyze_wildcard'
        - $ref: '#/components/parameters/search___query.analyzer'
        - $ref: '#/components/parameters/search___query.expand_wildcards'
    post:
      operationId: search.3
      x-operation-group: search
      x-version-added: '1.0'
      description: Returns results matching a query.
      externalDocs:
        url: https://docs.opensearch.org/latest/api-reference/search/
      parameters:
        - $ref: '#/components/parameters/search___path.index'
        - $ref: '#/components/parameters/search___query.analyze_wildcard'
        - $ref: '#/components/parameters/search___query.analyzer'
        - $ref: '#/components/parameters/search___query.expand_wildcards'
components:

  parameters:

    _global___query.pretty:
      name: pretty
      in: query
      description: Whether to pretty format the returned JSON response.
      schema:
        type: boolean
      default: false
      x-global: true

    _global___query.human:
      name: human
      in: query
      description: Whether to return human readable values for statistics.
      schema:
        type: boolean
      default: true
      x-global: true
      deprecated: true
      x-version-deprecated: '3.0'
      x-deprecation-message: Use the `format` parameter instead.

    cat.health___query.expand_wildcard:
      in: query
      required: true
      name: expand_wildcard
      description: |-
          Whether to expand wildcard expression to concrete indices that are open, closed, or both.
          For more information, see [cat health API](https://docs.opensearch.org/latest/api-reference/cat/health/).
      schema:
        oneOf:
          - type: string
            const: open
            description: Expand wildcards to open indices only.
          - type: string
            const: closed
            description: Expand wildcards to closed indices only.
          - type: string
            const: master
            description: Expand wildcards for master nodes only.

    search___path.index:
      in: path
      name: index
      description: |-
        Comma-separated list of data streams, indexes, and aliases to search.
        Supports wildcards (`*`).
        To search all data streams and indexes, omit this parameter or use `*` or `_all`.
      required: true
      schema:
        $ref: '#/components/schemas/_common___Indices'
      style: simple

    search___query.analyze_wildcard:
      in: query
      name: analyze_wildcard
      required: true
      description: |-
        If true, wildcard and prefix queries are analyzed.
        This parameter can only be used when the q query string parameter is specified.
      schema:
        type: boolean
        default: false
      style: form

    search___query.analyzer:
      in: query
      name: analyzer
      description: |-
        Analyzer to use for the query string.
        This parameter can only be used when the q query string parameter is specified.
      schema:
        type: string
      style: form

    search___query.expand_wildcards:
      in: query
      name: expand_wildcards
      description: |-
        Comma-separated list of expand wildcard options.
      schema:
        oneOf:
          - $ref: '#/components/schemas/_common___ExpandWildcardsCompact'
          - type: array
            items:
              $ref: '#/components/schemas/_common___ExpandWildcardsCompact'

  schemas:

    _common___Indices:
      oneOf:
        - $ref: '#/components/schemas/_common___IndexName'
        - $ref: '#/components/schemas/_common___SpecialIndices'
        - type: array
          items:
            $ref: '#/components/schemas/_common___IndexName'

    _common___IndexName:
      type: string

    _common___SpecialIndices:
      oneOf:
        - type: string
          const: _all
        - type: string
          const: _any
        - type: string
          const: _none

    _common___ExpandWildcardsCompact:
      type: string
      enum:
        - open
        - closed
        - none
        - all
