name: Jekyll Build Verification

on: [pull_request]

jobs:
  jekyll-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
    - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1
      with:
        ruby-version: '3.4.5'
        bundler-cache: true
    - run: |
        JEKYLL_FATAL_LINK_CHECKER=internal bundle exec jekyll build --future