name: Lint and Test Jekyll Spec Insert
on:
  push:
    paths:
      - 'spec-insert/**'
  pull_request:
    paths:
      - 'spec-insert/**'
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1
        with: 
          ruby-version: '3.4.5'
      - run: bundle install
      - working-directory: spec-insert
        run: |
          bundle exec rubocop
          bundle exec rspec
