name: Style Check

on:
  pull_request:
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write

jobs:
  style-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
          
      - name: Run Vale
        uses: errata-ai/vale-action@85f9f7f2c5f449ac0ae5b66662961bae3f77ca6a # reviewdog
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          fail_on_error: false
          reporter: github-pr-check
          filter_mode: added
          vale_flags: "--no-exit"
          version: 2.28.0
        continue-on-error: true
